//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinephile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coutries
    {
        public Coutries()
        {
            this.Artists = new HashSet<Artists>();
            this.Movies = new HashSet<Movies>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Artists> Artists { get; set; }
        public virtual ICollection<Movies> Movies { get; set; }
    }
}
