//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinephile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public Movies()
        {
            this.Ratings = new HashSet<Ratings>();
            this.Reviews = new HashSet<Reviews>();
            this.Actors = new HashSet<Artists>();
            this.Coutries = new HashSet<Coutries>();
            this.Directors = new HashSet<Artists>();
            this.Genres = new HashSet<Genres>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Storyline { get; set; }
        public System.DateTime ReleseDate { get; set; }
        public int RunningTime { get; set; }
        public int LanguageId { get; set; }
        public string PosterPath { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual ICollection<Artists> Actors { get; set; }
        public virtual ICollection<Coutries> Coutries { get; set; }
        public virtual ICollection<Artists> Directors { get; set; }
        public virtual ICollection<Genres> Genres { get; set; }
    }
}
